name: MYCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo $PATH
        node -v
        npm -v
        python --version
        java -version
        go version
        docker version
        git version
